In [13]:
import pandas as pd

df = pd.read_csv('student_data.csv')

ascending depend on Data Structure Marks col

In [ ]:
copy = df.sort_values('Data Structure Marks')
copy


# df.sort_values('Data Structure Marks', inplace=TabError)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

descending depend on Data Structure Marks col

In [3]:
copy = df.sort_values('Data Structure Marks', ascending=False)
copy

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

combine sort, if same then val for ds then go algo else first ds then algo

In [4]:
copy = df.sort_values(['Data Structure Marks', 'Algorithm Marks'], ascending=False)
copy

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

In [15]:
# Data Structure Marks: descending (largest → smallest)
# Algorithm Marks: asc
#
# 0 → False → descending
# 1 → True → ascending

copy2 = df.sort_values(
    ['Data Structure Marks', 'Python Marks'], 
    ascending=[0,1]
    # ascending=[False, True]
    )
copy2

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram